
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/globals.css'

export function generateStaticParams() {
  return [{locale: 'en'}, {locale: 'vi'}];
}

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({children, params}:{
  children: React.ReactNode,
  params : any
}) {
 
  return (
    <html lang={params.locale}>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
