export const RememberMe:string = "rememberme";
export const URL_PREFIX:string = "http://192.168.1.18:8080/"
export const SUCCESS_STATUS:string = "SUCCESS"

export const ACTIVE_EMAIL:string = "active_email"
export const ACCESS_TOKEN:string = "actk"
export const REFRES_TOKEN:string = "rftk"
export const LOCAL_USER:string = "currentUser"
export const LOCAL_WS:string = "localWs"
export const LOCAL_NOTE:string = "currentNote"
export const CURRENT_NOTE:string = "currentWs"
export const CURRENT_PERCENT:string = "currentPercent"
export const CHECK_TYPE:string = "CHECK"
export const NOTE_TYPE:string = "NOTE"
export const SORT_ITEMS:string = "sort_items"
export const SORT_TASK_ITEMS:string = "sort_task_items"
export const SELECTED_SORT:string = "selected_sort"
export const SELECTED_TASK_SORT:string = "selected_task_sort"

export const EXPAND_SIDEBAR:string = "expand_sidebar"
export const HOMEPAGE_ANALYTICS:string = "homepage_analytics"
export const DETAILPAGE_ANALYTICS:string = "detailpage_analytics"
export const IS_REMEMBER:string = "isRememberMe"
export const USERNAME_LOCAL:string = "uname_local"